StyleCI/StyleCI

- app/Http/Controllers/GitHubController.php
> Added Docbloc to missing functions

- resources/assets/sass/modules/_badges.scss
- resources/assets/sass/modules/_syntax.scss
- resources/assets/sass/modules/_variables.scss
- resources/assets/sass/pages/_commit.scss
- resources/assets/sass/pages/_repos.scss
- resources/assets/sass/partials/_navbar.scss
- resources/assets/sass/partials/_page-heading.scss
- resources/views/commit.blade.php
- resources/views/index.blade.php
Remaining fixes @joecohens. :)
> Tabs to spaces

- app/Models/Commit.php
- resources/views/repo.blade.php
Fixes https://github.com/StyleCI/StyleCI/issues/19 and https://github.com/StyleCI/StyleCI/issues/18
> Fix time in seconds and remove branch from view

- app/Http/Controllers/CommitController.php
- app/Http/routes.php
Continue https://github.com/StyleCI/StyleCI/issues/15
> Added commit controller

- resources/views/commit.blade.php
> Shows the repo name of the commit, closes #35

- app/GitHub/Repos.php
I haven't tested this, but I'm pretty sure this is faster. We've only got one db hit now.
> Improved repo listing performance

- resources/views/commit.blade.php
Closes https://github.com/StyleCI/StyleCI/issues/52
> Remove line numbers from diff view

- app/Handlers/Commands/LoginCommandHandler.php
- app/Http/routes.php
- database/migrations/2015_01_24_072255_create_users_table.php
- resources/views/account.blade.php
I'm going to re-write this at a later point. I want users to be able to have multiple api keys, and configure the permissions for each key.
> Remove the crappy rest api for now

- app/Events/AnalysisHasCompletedEvent.php
- app/Events/RepoWasDisabledEvent.php
- app/Events/RepoWasEnabledEvent.php
- app/Events/UserHasRageQuitEvent.php
- app/Events/UserHasSignedUpEvent.php
- app/Handlers/Commands/AnalyseCommitCommandHandler.php
- app/Handlers/Commands/DeleteAccountCommandHandler.php
- app/Handlers/Commands/DisableRepoCommandHandler.php
- app/Handlers/Commands/EnableRepoCommandHandler.php
- app/Handlers/Commands/LoginCommandHandler.php
- app/Handlers/Events/AnalysisNotificationsHandler.php
- app/Handlers/Events/CommitStatusHandler.php
- app/Handlers/Events/DisableHooksHandler.php
- app/Handlers/Events/EnableHooksHandler.php
- app/Providers/EventServiceProvider.php
Moved some stuff out to event handlers. This should make the notifications stuff easier.
> Event Based Refactor

- app/Http/Controllers/RepoController.php
The repo list should only show repos the user has admin access to.
Fixes #51.
> Fixed the repo list

- app/Http/Controllers/AccountController.php
- app/Http/routes.php
- resources/views/account.blade.php
> Support Account Deletion

- app/Handlers/Commands/AnalyseCommitCommandHandler.php
- app/Models/Commit.php
- app/Models/User.php
- app/Presenters/CommitPresenter.php
- app/Presenters/UserPresenter.php
- composer.json
- composer.lock
- config/app.php
- resources/views/account.blade.php
- resources/views/repo.blade.php
- resources/views/repos.blade.php
Let's pull in and use my model presenter package. Closes #72.
// cc @jbrooksuk, @joecohens.
> Use Model Presenters

- app/Handlers/Middleware/UseDatabaseTransaction.php
- app/Providers/BusServiceProvider.php
> Pipe commands through a db transaction

- resources/assets/sass/modules/_syntax.scss
This **should** fix the error presented by Issue #56. I don't have a compiler for sass to css set up, so that's the only thing that should need done.
> Fix to the Double Scroller

- app/Console/Commands/AnalyseAllCommand.php
- app/Console/Commands/AnalyseRepoCommand.php
- app/GetCommitTrait.php
- app/Http/Controllers/AccountController.php
- app/Http/Controllers/RepoController.php
- app/Http/routes.php
- resources/assets/sass/pages/_repo.scss
- resources/views/repo.blade.php
@joecohens The front end stuff needs dealing with. We should probably refresh the page after the analysis has been queued.
NB, I will be changing the backend to ditch the trait at some point, but I don't feel like that's a priority right now. I want to ship this. :)
---
Closes #57.
> Manual Analysis Support

- app/Http/Controllers/RepoController.php
- resources/views/repo.blade.php
Closes https://github.com/StyleCI/StyleCI/issues/21
> Pagination on commit list

- database/migrations/2015_01_18_120400_create_repos_table.php
- database/migrations/2015_01_18_120401_create_commits_table.php
- database/migrations/2015_01_18_120402_create_forks_table.php
- database/migrations/2015_01_24_072255_create_users_table.php
Closes #98.
NB I couldn't index fork_id, because it's nullable.
// cc @jbrooksuk
> Improved Migrations

- app/Handlers/Events/RealTimeStatusHandler.php
> Fix: Argument is $event, doc-block says $event

- README.md
Fixed a typo in the readme.md file.
> Typo in the readme file

- app/Events/AnalysisWasQueuedEvent.php
- app/Handlers/Events/RealTimeStatusHandler.php
- app/Providers/EventServiceProvider.php
- resources/assets/js/app.js
> Let pusher know about new pending analyses

- app/Events/UserHasLoggedInEvent.php
- app/Handlers/Commands/LoginCommandHandler.php
- app/Handlers/Events/RepoCacheFlushHandler.php
- app/Providers/EventServiceProvider.php
> Flush repo cache on login

- app/Http/Controllers/AccountController.php
- app/Http/Controllers/AuthController.php
- app/Http/Controllers/RepoController.php
- app/Http/Kernel.php
- app/Http/Middleware/VerifyCsrfToken.php
Closes https://github.com/StyleCI/StyleCI/issues/119
> Added csrf protection rules to controllers

- app/GitHub/Commits.php
- app/Providers/GitHubServiceProvider.php
- app/Providers/RepositoryServiceProvider.php
- app/Repositories/CommitRepository.php
> Fetch commit message from github when performing manual analyses

- app/GitHub/ClientFactory.php
- app/GitHub/Tokens.php
- app/Handlers/Events/RevokeTokenHandler.php
- app/Providers/EventServiceProvider.php
- app/Providers/GitHubServiceProvider.php
- composer.json
- composer.lock
- config/github.php
Closes #124.
I've emailed @pengwynn regarding basic authentication not working.
> Revoke token on account deletion

- app/GitHub/Repos.php
- app/Http/Controllers/AccountController.php
- app/Repositories/RepoRepository.php
Closes #137.
Closes #138.
// cc @trizz
> Fixes issues with admin access to repos

- resources/views/repo.blade.php
> Only user can analyse repo on demand

- resources/views/partials/header.blade.php
See differences here: https://i.starbs.net/p7Er
> Changed description to better match GitHub's META

- resources/views/account.blade.php
It's a nice statistic to display.
> Show many repositories the user has in their profile

- resources/assets/sass/partials/_page-heading.scss
I've went ahead and applied the background image on the homepage to the sub-pages in the page headings to create an awe-aspiring effect! Take a gander:
> Added the background to page-heading

- app/Handlers/Events/AnalysisNotificationsHandler.php
- resources/views/emails/errored-html.blade.php
- resources/views/emails/errored-text.php
- resources/views/emails/misconfigured-html.blade.php
- resources/views/emails/misconfigured-text.php
> Email people for all failed analyses

- app/Handlers/Commands/LoginCommandHandler.php
- app/Http/Controllers/AuthController.php
> Filter User's Names

- app/Http/Controllers/AuthController.php
I've updated the `$raw` variable to `$user` in `AuthController`. Weren't possible to login. 
This fixes a bug introduced in #250.
> Fix $raw variable in AuthController.

- resources/views/commit.blade.php
Closes https://github.com/StyleCI/StyleCI/issues/259
> Embed shield badge methods modal

- app/Handlers/Commands/AnalyseCommitCommandHandler.php
- app/Models/Commit.php
- app/Presenters/CommitPresenter.php
- database/migrations/2015_05_22_072625_add_error_message_to_commits_table.php
- resources/views/commit.blade.php
This is a proof of concept to show a detailed error message for misconfiguration.
I'm no Laravel expert so I'm not sure if everything is correct :)
> Show detailed error when configuration is invalid

- app/Events/AnalysisHasStartedEvent.php
- app/Handlers/Commands/AnalyseCommitCommandHandler.php
- app/Handlers/Events/AnalysisLoggingHandler.php
- app/Handlers/Events/ExceptionLoggingHandler.php
- app/Providers/EventServiceProvider.php
> Better events and logging

- app/Commit/Diff.php
- app/Presenters/CommitPresenter.php
- resources/views/commit.blade.php
/cc @GrahamCampbell @jbrooksuk
> Extracted more information from diff

- app/Commands/CleanupCommitCommand.php
- app/Console/Commands/CleanupCommand.php
- app/Console/Kernel.php
- app/Events/CleanupHasCompletedEvent.php
- app/Handlers/Commands/AnalyseCommitCommandHandler.php
- app/Handlers/Commands/CleanupCommitCommandHandler.php
- app/Handlers/Events/AnalysisLoggingHandler.php
- app/Handlers/Events/AnalysisNotificationsHandler.php
- app/Handlers/Events/AuthenticationHandler.php
- app/Handlers/Events/CommitStatusHandler.php
- app/Handlers/Events/DisableHooksHandler.php
- app/Handlers/Events/EnableHooksHandler.php
- app/Handlers/Events/FailedJobLoggingHandler.php
- app/Handlers/Events/RealTimeRepoHandler.php
- app/Handlers/Events/RealTimeStatusHandler.php
- app/Handlers/Events/RepoCacheFlushHandler.php
- app/Handlers/Events/RevokeTokenHandler.php
- app/Handlers/Events/WelcomeMessageHandler.php
- app/Providers/EventServiceProvider.php
Closes #354.
Ping @joecohens for review. :)
> Added commit cleanups after time outs

- app/GitHub/Repos.php
- app/Handlers/Events/RealTimeStatusHandler.php
- app/Http/Controllers/RepoController.php
- app/Http/Controllers/ShieldController.php
- app/Models/Repo.php
- database/migrations/2015_06_03_233242_add_default_branch_to_repos_table.php
- resources/views/account.blade.php
- resources/views/repos.blade.php
> Read the default branch from github

- app/Handlers/Events/GoodbyeMessageHandler.php
- app/Providers/EventServiceProvider.php
- resources/views/emails/goodbye-html.blade.php
- resources/views/emails/goodbye-text.blade.php
This is completely untested because my dev env b0rked.
> Goodbye Email

- app/GitHub/Repos.php
This should be merged on [June 24th](https://developer.github.com/changes/2015-06-10-breaking-changes-to-organization-permissions-coming-on-june-24).
> Remove moondragon preview

- app/Handlers/Events/RepoToggledNotificationHandler.php
- app/Providers/EventServiceProvider.php
- resources/views/emails/disabled-html.blade.php
- resources/views/emails/disabled-text.php
- resources/views/emails/enabled-html.blade.php
- resources/views/emails/enabled-text.php
> Email all collaborators when a repo is disabled/enabled

- app/Handlers/Commands/CleanupAnalysisCommandHandler.php
- app/Handlers/Commands/RunAnalysisCommandHandler.php
- app/Models/Analysis.php
- app/Models/Repo.php
- app/Models/User.php
- app/Presenters/AnalysisPresenter.php
- database/migrations/2015_06_30_120801_create_analyses_table.php
- resources/views/analysis.blade.php
> Cleanup model properties

- app/Commands/AnalyseBranchCommand.php
- app/Commands/AnalyseCommitCommand.php
- app/Commands/AnalysePullRequestCommand.php
- app/Handlers/Commands/EnableRepoCommandHandler.php
- app/Http/Controllers/GitHubController.php
- app/Http/Controllers/RepoController.php
- app/Models/Repo.php
- app/Presenters/Diff.php
- app/Presenters/RepoPresenter.php
- database/migrations/2015_06_30_120800_create_repos_table.php
> Security Improvements

- app/Presenters/RepoPresenter.php
- resources/views/analysis.blade.php
- resources/views/repos.blade.php
> Fix analysis channel id, fix repos message

- app/Console/Commands/GarbageCollectCommand.php
- app/GitHub/Status.php
- app/Handlers/Commands/CleanupAnalysisCommandHandler.php
- app/Handlers/Commands/DisableRepoCommandHandler.php
- app/Handlers/Commands/RunAnalysisCommandHandler.php
- app/Handlers/Events/AnalysisLoggingHandler.php
- app/Handlers/Events/AnalysisNotificationsHandler.php
- app/Models/Analysis.php
- app/Presenters/AnalysisPresenter.php
- composer.json
- composer.lock
- database/migrations/2015_06_30_120801_create_analyses_table.php
- resources/views/analysis.blade.php
- storage/fixers/.gitignore
Closes #96. Closes #400. Closes #401.
> Many New Things

- app/Presenters/RepoPresenter.php
// cc @joecohens 
This was broken before if there was no last analysis.
> Fixed last_analysis presentation from the repo presenter

- app/GitHub/Branches.php
- app/Providers/GitHubServiceProvider.php
> Added branch caching

- app/Http/Controllers/AuthController.php
> If the user can't see any repos, send to account page on login

- app/Presenters/AnalysisPresenter.php
- app/Presenters/RepoPresenter.php
- app/Presenters/UserPresenter.php
> Make presenter methods protected

- resources/views/repo.blade.php
- resources/views/repos.blade.php
This should escape the commit messages.
> Escape lodash tempalte

- app/Handlers/Events/Analysis/PusherStatusHandler.php
- app/Handlers/Events/Repo/PusherBranchHandler.php
- app/Handlers/Events/Repo/PusherRepoHandler.php
- app/Providers/EventServiceProvider.php
- resources/assets/js/app.js
- resources/assets/js/components/analysis.js
- resources/assets/js/components/repo.js
- resources/assets/js/components/repos.js
I feel this is less confusing for us to manage.
> Rename realtime stuff to pusher

- app/Console/Commands/CleanupCommand.php
- app/Handlers/Commands/Analysis/AnalyseBranchCommandHandler.php
- app/Handlers/Commands/Analysis/AnalyseCommitCommandHandler.php
- app/Handlers/Commands/Analysis/AnalysePullRequestCommandHandler.php
- app/Handlers/Events/Analysis/AnalysisMailHandler.php
- app/Handlers/Events/Repo/AnalysisVisibilityHandler.php
- app/Http/Controllers/Api/RepoController.php
- app/Models/Analysis.php
- app/Models/Repo.php
- app/Providers/EventServiceProvider.php
- database/migrations/2015_06_30_120801_create_analyses_table.php
- tests/Models/AnalysisTest.php
> Mark analyses as invisible if their branch is deleted

- app/GitHub/Status.php
> Show the number of files through github status

- app/Exceptions/Displayers/RedirectDisplayer.php
- app/Http/Controllers/AuthController.php
- config/exceptions.php
> Attempt to log users in on 401

- app/GitHub/Status.php
The correct messages are:
* 1 file needs addressing
* 2 files need addressing
* 3 files need addressing
Not: 1 files need addressing...
> Fix the status message for 1 file

- resources/views/emails/html/access.blade.php
- resources/views/emails/html/disabled.blade.php
- resources/views/emails/html/enabled.blade.php
- resources/views/emails/html/errored.blade.php
- resources/views/emails/html/failed.blade.php
- resources/views/emails/html/first.blade.php
- resources/views/emails/html/misconfigured.blade.php
- resources/views/emails/html/passed.blade.php
- resources/views/emails/html/timeout.blade.php
- resources/views/emails/html/welcome.blade.php
- resources/views/emails/text/access.blade.php
- resources/views/emails/text/errored.blade.php
- resources/views/emails/text/welcome.blade.php
Bold tags, re-word the welcome email.
> Update email content

- resources/assets/js/components/analysis.js
- resources/assets/js/components/repo.js
- resources/assets/js/components/repos.js
- resources/views/analysis/index.blade.php
- resources/views/repos/repo.blade.php
/cc @GrahamCampbell 
Closes https://github.com/StyleCI/StyleCI/issues/497. Closes https://github.com/StyleCI/StyleCI/issues/498.
> Lazy load diff and js fixes

- app/GitHub/Branches.php
- app/GitHub/Collaborators.php
- app/GitHub/Commits.php
- app/GitHub/Hooks.php
- app/GitHub/Status.php
> Stop using quicksilver preview

- resources/views/repos/repo.blade.php
> Fixed typo

- resources/assets/js/app.js
> Fixed up data-method stuff

- app/Commands/Analysis/DeleteAnalysisCommand.php
- app/Handlers/Commands/Analysis/DeleteAnalysisCommandHandler.php
- app/Handlers/Commands/Repo/DisableRepoCommandHandler.php
- tests/Commands/Analysis/DeleteAnalysisCommandTest.php
This is particularly useful in tinker when I want to delete an analysis.
> Implement analysis deletion through a command

- app/Http/Controllers/Api/RepoController.php
> Fixed repo list performance issues

- composer.json
- composer.lock
Simelar to https://github.com/cachethq/Cachet/pull/978.
> Force lock file to work on php 5.6.4

- elixir.json
- gulpfile.js
- package.json
> Update to elixir 3.3.1, removed unused elixir.json

- resources/assets/js/components/analysis.js
> No editing the diff file

- app/Handlers/Events/Analysis/CleanupHandler.php
- app/Handlers/Events/Repo/CleanupHandler.php
https://github.com/paragonie/random_compat ensures that this function is available on PHP 5.6, and in PHP 7.0, it's natively implemented.
> Use random_int rather than mt_rand

- resources/views/partials/header.blade.php
> Updated cookie consent
